import {
  Coffee,
  Fan,
  Rabbit,
  Sprout,
  BedDouble,
  Car,
  Bath,
  Bike,
  Bug,
  Cat,
  Dog,
  Droplets,
  Flame,
  Flower2,
  Fish,
  Fuel,
  Hammer,
  Heater,
  Lightbulb,
  Wrench,
  WashingMachine,
  Refrigerator,
  Microwave,
  Trash2,
  Sofa,
  ShowerHead,
  Toilet,
  Wind,
  Zap,
  Leaf,
  TreePine,
  PawPrint,
  Bird,
  Shirt,
  Scissors,
  Brush,
  PaintRoller,
  Plug,
  Key,
  DoorOpen,
  Home,
  Package,
  Pill,
  Stethoscope,
  Utensils,
  CookingPot,
  Wine,
  Baby,
  Gamepad2,
  Laptop,
  Printer,
  Smartphone,
  Watch,
  Snowflake,
  SunMedium,
  Umbrella,
  Battery,
  Recycle,
  Sparkles,
  type LucideIcon,
} from "lucide-react";

export interface IconEntry {
  key: string;
  Icon: LucideIcon;
  keywords: string;
}

export const ICONS: IconEntry[] = [
  { key: "Coffee", Icon: Coffee, keywords: "coffee kawa ekspres napój" },
  { key: "Fan", Icon: Fan, keywords: "fan wentylacja hvac filtr powietrze" },
  { key: "Rabbit", Icon: Rabbit, keywords: "rabbit królik zwierzę klatka" },
  { key: "Sprout", Icon: Sprout, keywords: "plant roślina podlewanie sprout" },
  { key: "BedDouble", Icon: BedDouble, keywords: "bed łóżko pościel sypialnia" },
  { key: "Car", Icon: Car, keywords: "car auto samochód przegląd" },
  { key: "Bath", Icon: Bath, keywords: "bath wanna łazienka clean" },
  { key: "Bike", Icon: Bike, keywords: "bike rower" },
  { key: "Bug", Icon: Bug, keywords: "bug owady dezynsekcja" },
  { key: "Cat", Icon: Cat, keywords: "cat kot zwierzę" },
  { key: "Dog", Icon: Dog, keywords: "dog pies zwierzę" },
  { key: "Droplets", Icon: Droplets, keywords: "water woda clean mycie" },
  { key: "Flame", Icon: Flame, keywords: "fire piec ogrzewanie gaz" },
  { key: "Flower2", Icon: Flower2, keywords: "flower kwiat ogród" },
  { key: "Fish", Icon: Fish, keywords: "fish akwarium ryby" },
  { key: "Fuel", Icon: Fuel, keywords: "fuel paliwo tankowanie" },
  { key: "Hammer", Icon: Hammer, keywords: "hammer naprawa remont" },
  { key: "Heater", Icon: Heater, keywords: "heater kaloryfer ogrzewanie" },
  { key: "Lightbulb", Icon: Lightbulb, keywords: "light żarówka światło" },
  { key: "Wrench", Icon: Wrench, keywords: "wrench serwis naprawa klucz" },
  { key: "WashingMachine", Icon: WashingMachine, keywords: "washing pralka pranie" },
  { key: "Refrigerator", Icon: Refrigerator, keywords: "fridge lodówka clean" },
  { key: "Microwave", Icon: Microwave, keywords: "microwave mikrofala piekarnik" },
  { key: "Trash2", Icon: Trash2, keywords: "trash śmieci kosz" },
  { key: "Sofa", Icon: Sofa, keywords: "sofa kanapa salon" },
  { key: "ShowerHead", Icon: ShowerHead, keywords: "shower prysznic clean" },
  { key: "Toilet", Icon: Toilet, keywords: "toilet toaleta wc clean" },
  { key: "Wind", Icon: Wind, keywords: "wind wietrzenie powietrze" },
  { key: "Zap", Icon: Zap, keywords: "zap prąd energia" },
  { key: "Leaf", Icon: Leaf, keywords: "leaf liście ogród" },
  { key: "TreePine", Icon: TreePine, keywords: "tree drzewo ogród" },
  { key: "PawPrint", Icon: PawPrint, keywords: "paw łapa zwierzę" },
  { key: "Bird", Icon: Bird, keywords: "bird ptak klatka" },
  { key: "Shirt", Icon: Shirt, keywords: "shirt ubrania pranie" },
  { key: "Scissors", Icon: Scissors, keywords: "scissors strzyżenie przycinanie" },
  { key: "Brush", Icon: Brush, keywords: "brush czyszczenie clean szczotka" },
  { key: "PaintRoller", Icon: PaintRoller, keywords: "paint malowanie remont" },
  { key: "Plug", Icon: Plug, keywords: "plug gniazdko prąd" },
  { key: "Key", Icon: Key, keywords: "key klucz zamek" },
  { key: "DoorOpen", Icon: DoorOpen, keywords: "door drzwi" },
  { key: "Home", Icon: Home, keywords: "home dom" },
  { key: "Package", Icon: Package, keywords: "package paczka dostawa" },
  { key: "Pill", Icon: Pill, keywords: "pill leki tabletki" },
  { key: "Stethoscope", Icon: Stethoscope, keywords: "health zdrowie wizyta lekarz" },
  { key: "Utensils", Icon: Utensils, keywords: "utensils jedzenie sztućce" },
  { key: "CookingPot", Icon: CookingPot, keywords: "pot garnek gotowanie" },
  { key: "Wine", Icon: Wine, keywords: "wine wino napoje" },
  { key: "Baby", Icon: Baby, keywords: "baby dziecko" },
  { key: "Gamepad2", Icon: Gamepad2, keywords: "game konsola" },
  { key: "Laptop", Icon: Laptop, keywords: "laptop komputer backup" },
  { key: "Printer", Icon: Printer, keywords: "printer drukarka tusz" },
  { key: "Smartphone", Icon: Smartphone, keywords: "phone telefon" },
  { key: "Watch", Icon: Watch, keywords: "watch zegarek bateria" },
  { key: "Snowflake", Icon: Snowflake, keywords: "snow zima klimatyzacja" },
  { key: "SunMedium", Icon: SunMedium, keywords: "sun lato słońce" },
  { key: "Umbrella", Icon: Umbrella, keywords: "umbrella deszcz" },
  { key: "Battery", Icon: Battery, keywords: "battery bateria wymiana" },
  { key: "Recycle", Icon: Recycle, keywords: "recycle segregacja śmieci" },
  { key: "Sparkles", Icon: Sparkles, keywords: "sparkles sprzątanie clean" },
];

const MAP = new Map(ICONS.map((i) => [i.key, i.Icon]));

export function getIcon(key: string): LucideIcon {
  return MAP.get(key) ?? Sparkles;
}
