/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CookbookRouteImport } from './routes/cookbook'
import { Route as CookbookIndexRouteImport } from './routes/cookbook.index'
import { Route as CookbookRecipeIdRouteImport } from './routes/cookbook.$recipeId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CookbookRoute = CookbookRouteImport.update({
  id: '/cookbook',
  path: '/cookbook',
  getParentRoute: () => rootRouteImport,
} as any)
const CookbookIndexRoute = CookbookIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CookbookRoute,
} as any)
const CookbookRecipeIdRoute = CookbookRecipeIdRouteImport.update({
  id: '/$recipeId',
  path: '/$recipeId',
  getParentRoute: () => CookbookRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cookbook': typeof CookbookRouteWithChildren
  '/cookbook/$recipeId': typeof CookbookRecipeIdRoute
  '/cookbook/': typeof CookbookIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cookbook/$recipeId': typeof CookbookRecipeIdRoute
  '/cookbook': typeof CookbookIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cookbook': typeof CookbookRouteWithChildren
  '/cookbook/$recipeId': typeof CookbookRecipeIdRoute
  '/cookbook/': typeof CookbookIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/cookbook' | '/cookbook/$recipeId' | '/cookbook/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/cookbook/$recipeId' | '/cookbook'
  id: '__root__' | '/' | '/cookbook' | '/cookbook/$recipeId' | '/cookbook/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CookbookRoute: typeof CookbookRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookbook': {
      id: '/cookbook'
      path: '/cookbook'
      fullPath: '/cookbook'
      preLoaderRoute: typeof CookbookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookbook/': {
      id: '/cookbook/'
      path: '/'
      fullPath: '/cookbook/'
      preLoaderRoute: typeof CookbookIndexRouteImport
      parentRoute: typeof CookbookRoute
    }
    '/cookbook/$recipeId': {
      id: '/cookbook/$recipeId'
      path: '/$recipeId'
      fullPath: '/cookbook/$recipeId'
      preLoaderRoute: typeof CookbookRecipeIdRouteImport
      parentRoute: typeof CookbookRoute
    }
  }
}

interface CookbookRouteChildren {
  CookbookRecipeIdRoute: typeof CookbookRecipeIdRoute
  CookbookIndexRoute: typeof CookbookIndexRoute
}

const CookbookRouteChildren: CookbookRouteChildren = {
  CookbookRecipeIdRoute: CookbookRecipeIdRoute,
  CookbookIndexRoute: CookbookIndexRoute,
}

const CookbookRouteWithChildren = CookbookRoute._addFileChildren(
  CookbookRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CookbookRoute: CookbookRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
