/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CookbookRouteImport } from './routes/cookbook'
import { Route as InsightsRouteImport } from './routes/insights'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ShoppingRouteImport } from './routes/shopping'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as CookbookIndexRouteImport } from './routes/cookbook.index'
import { Route as CookbookRecipeIdRouteImport } from './routes/cookbook.$recipeId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CookbookRoute = CookbookRouteImport.update({
  id: '/cookbook',
  path: '/cookbook',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightsRoute = InsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ShoppingRoute = ShoppingRouteImport.update({
  id: '/shopping',
  path: '/shopping',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const CookbookIndexRoute = CookbookIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CookbookRoute,
} as any)
const CookbookRecipeIdRoute = CookbookRecipeIdRouteImport.update({
  id: '/$recipeId',
  path: '/$recipeId',
  getParentRoute: () => CookbookRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cookbook': typeof CookbookRouteWithChildren
  '/insights': typeof InsightsRoute
  '/login': typeof LoginRoute
  '/shopping': typeof ShoppingRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/cookbook/$recipeId': typeof CookbookRecipeIdRoute
  '/cookbook/': typeof CookbookIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/insights': typeof InsightsRoute
  '/login': typeof LoginRoute
  '/shopping': typeof ShoppingRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/cookbook/$recipeId': typeof CookbookRecipeIdRoute
  '/cookbook': typeof CookbookIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cookbook': typeof CookbookRouteWithChildren
  '/insights': typeof InsightsRoute
  '/login': typeof LoginRoute
  '/shopping': typeof ShoppingRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/cookbook/$recipeId': typeof CookbookRecipeIdRoute
  '/cookbook/': typeof CookbookIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cookbook'
    | '/insights'
    | '/login'
    | '/shopping'
    | '/auth/callback'
    | '/cookbook/$recipeId'
    | '/cookbook/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/insights'
    | '/login'
    | '/shopping'
    | '/auth/callback'
    | '/cookbook/$recipeId'
    | '/cookbook'
  id:
    | '__root__'
    | '/'
    | '/cookbook'
    | '/insights'
    | '/login'
    | '/shopping'
    | '/auth/callback'
    | '/cookbook/$recipeId'
    | '/cookbook/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CookbookRoute: typeof CookbookRouteWithChildren
  InsightsRoute: typeof InsightsRoute
  LoginRoute: typeof LoginRoute
  ShoppingRoute: typeof ShoppingRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookbook': {
      id: '/cookbook'
      path: '/cookbook'
      fullPath: '/cookbook'
      preLoaderRoute: typeof CookbookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights': {
      id: '/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof InsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shopping': {
      id: '/shopping'
      path: '/shopping'
      fullPath: '/shopping'
      preLoaderRoute: typeof ShoppingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookbook/': {
      id: '/cookbook/'
      path: '/'
      fullPath: '/cookbook/'
      preLoaderRoute: typeof CookbookIndexRouteImport
      parentRoute: typeof CookbookRoute
    }
    '/cookbook/$recipeId': {
      id: '/cookbook/$recipeId'
      path: '/$recipeId'
      fullPath: '/cookbook/$recipeId'
      preLoaderRoute: typeof CookbookRecipeIdRouteImport
      parentRoute: typeof CookbookRoute
    }
  }
}

interface CookbookRouteChildren {
  CookbookRecipeIdRoute: typeof CookbookRecipeIdRoute
  CookbookIndexRoute: typeof CookbookIndexRoute
}

const CookbookRouteChildren: CookbookRouteChildren = {
  CookbookRecipeIdRoute: CookbookRecipeIdRoute,
  CookbookIndexRoute: CookbookIndexRoute,
}

const CookbookRouteWithChildren = CookbookRoute._addFileChildren(
  CookbookRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CookbookRoute: CookbookRouteWithChildren,
  InsightsRoute: InsightsRoute,
  LoginRoute: LoginRoute,
  ShoppingRoute: ShoppingRoute,
  AuthCallbackRoute: AuthCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
