/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccountRouteImport } from './routes/account'
import { Route as CookbookRouteImport } from './routes/cookbook'
import { Route as InsightsRouteImport } from './routes/insights'
import { Route as JoinRouteImport } from './routes/join'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ShoppingRouteImport } from './routes/shopping'
import { Route as WaitroomRouteImport } from './routes/waitroom'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as CookbookIndexRouteImport } from './routes/cookbook.index'
import { Route as CookbookRecipeIdRouteImport } from './routes/cookbook.$recipeId'
import { Route as CookbookNewRouteImport } from './routes/cookbook.new'
import { Route as CookbookTinsRouteImport } from './routes/cookbook.tins'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const CookbookRoute = CookbookRouteImport.update({
  id: '/cookbook',
  path: '/cookbook',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightsRoute = InsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinRoute = JoinRouteImport.update({
  id: '/join',
  path: '/join',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ShoppingRoute = ShoppingRouteImport.update({
  id: '/shopping',
  path: '/shopping',
  getParentRoute: () => rootRouteImport,
} as any)
const WaitroomRoute = WaitroomRouteImport.update({
  id: '/waitroom',
  path: '/waitroom',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const CookbookIndexRoute = CookbookIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CookbookRoute,
} as any)
const CookbookRecipeIdRoute = CookbookRecipeIdRouteImport.update({
  id: '/$recipeId',
  path: '/$recipeId',
  getParentRoute: () => CookbookRoute,
} as any)
const CookbookNewRoute = CookbookNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => CookbookRoute,
} as any)
const CookbookTinsRoute = CookbookTinsRouteImport.update({
  id: '/tins',
  path: '/tins',
  getParentRoute: () => CookbookRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/cookbook': typeof CookbookRouteWithChildren
  '/insights': typeof InsightsRoute
  '/join': typeof JoinRoute
  '/login': typeof LoginRoute
  '/shopping': typeof ShoppingRoute
  '/waitroom': typeof WaitroomRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/cookbook/$recipeId': typeof CookbookRecipeIdRoute
  '/cookbook/new': typeof CookbookNewRoute
  '/cookbook/tins': typeof CookbookTinsRoute
  '/cookbook/': typeof CookbookIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/insights': typeof InsightsRoute
  '/join': typeof JoinRoute
  '/login': typeof LoginRoute
  '/shopping': typeof ShoppingRoute
  '/waitroom': typeof WaitroomRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/cookbook/$recipeId': typeof CookbookRecipeIdRoute
  '/cookbook/new': typeof CookbookNewRoute
  '/cookbook/tins': typeof CookbookTinsRoute
  '/cookbook': typeof CookbookIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/cookbook': typeof CookbookRouteWithChildren
  '/insights': typeof InsightsRoute
  '/join': typeof JoinRoute
  '/login': typeof LoginRoute
  '/shopping': typeof ShoppingRoute
  '/waitroom': typeof WaitroomRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/cookbook/$recipeId': typeof CookbookRecipeIdRoute
  '/cookbook/new': typeof CookbookNewRoute
  '/cookbook/tins': typeof CookbookTinsRoute
  '/cookbook/': typeof CookbookIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/cookbook'
    | '/insights'
    | '/join'
    | '/login'
    | '/shopping'
    | '/waitroom'
    | '/auth/callback'
    | '/cookbook/$recipeId'
    | '/cookbook/new'
    | '/cookbook/tins'
    | '/cookbook/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/insights'
    | '/join'
    | '/login'
    | '/shopping'
    | '/waitroom'
    | '/auth/callback'
    | '/cookbook/$recipeId'
    | '/cookbook/new'
    | '/cookbook/tins'
    | '/cookbook'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/cookbook'
    | '/insights'
    | '/join'
    | '/login'
    | '/shopping'
    | '/waitroom'
    | '/auth/callback'
    | '/cookbook/$recipeId'
    | '/cookbook/new'
    | '/cookbook/tins'
    | '/cookbook/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  CookbookRoute: typeof CookbookRouteWithChildren
  InsightsRoute: typeof InsightsRoute
  JoinRoute: typeof JoinRoute
  LoginRoute: typeof LoginRoute
  ShoppingRoute: typeof ShoppingRoute
  WaitroomRoute: typeof WaitroomRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookbook': {
      id: '/cookbook'
      path: '/cookbook'
      fullPath: '/cookbook'
      preLoaderRoute: typeof CookbookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights': {
      id: '/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof InsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join': {
      id: '/join'
      path: '/join'
      fullPath: '/join'
      preLoaderRoute: typeof JoinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shopping': {
      id: '/shopping'
      path: '/shopping'
      fullPath: '/shopping'
      preLoaderRoute: typeof ShoppingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/waitroom': {
      id: '/waitroom'
      path: '/waitroom'
      fullPath: '/waitroom'
      preLoaderRoute: typeof WaitroomRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookbook/': {
      id: '/cookbook/'
      path: '/'
      fullPath: '/cookbook/'
      preLoaderRoute: typeof CookbookIndexRouteImport
      parentRoute: typeof CookbookRoute
    }
    '/cookbook/$recipeId': {
      id: '/cookbook/$recipeId'
      path: '/$recipeId'
      fullPath: '/cookbook/$recipeId'
      preLoaderRoute: typeof CookbookRecipeIdRouteImport
      parentRoute: typeof CookbookRoute
    }
    '/cookbook/new': {
      id: '/cookbook/new'
      path: '/new'
      fullPath: '/cookbook/new'
      preLoaderRoute: typeof CookbookNewRouteImport
      parentRoute: typeof CookbookRoute
    }
    '/cookbook/tins': {
      id: '/cookbook/tins'
      path: '/tins'
      fullPath: '/cookbook/tins'
      preLoaderRoute: typeof CookbookTinsRouteImport
      parentRoute: typeof CookbookRoute
    }
  }
}

interface CookbookRouteChildren {
  CookbookRecipeIdRoute: typeof CookbookRecipeIdRoute
  CookbookNewRoute: typeof CookbookNewRoute
  CookbookTinsRoute: typeof CookbookTinsRoute
  CookbookIndexRoute: typeof CookbookIndexRoute
}

const CookbookRouteChildren: CookbookRouteChildren = {
  CookbookRecipeIdRoute: CookbookRecipeIdRoute,
  CookbookNewRoute: CookbookNewRoute,
  CookbookTinsRoute: CookbookTinsRoute,
  CookbookIndexRoute: CookbookIndexRoute,
}

const CookbookRouteWithChildren = CookbookRoute._addFileChildren(
  CookbookRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  CookbookRoute: CookbookRouteWithChildren,
  InsightsRoute: InsightsRoute,
  JoinRoute: JoinRoute,
  LoginRoute: LoginRoute,
  ShoppingRoute: ShoppingRoute,
  WaitroomRoute: WaitroomRoute,
  AuthCallbackRoute: AuthCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
